name: Build and Publish Release

on:
  release:
    types: [created]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            old-name: minesweeper
            new-name: minesweeper-${{ github.event.release.tag_name }}-linux
          - os: windows-latest
            old-name: minesweeper.exe
            new-name: minesweeper-${{ github.event.release.tag_name }}-windows.exe
          - os: macos-latest
            old-name: minesweeper
            new-name: minesweeper-${{ github.event.release.tag_name }}-macos

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
          sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0

    - name: Build project
      run: |
        cargo build --release
        mv target/release/${{ matrix.old-name }} target/release/${{ matrix.new-name }}

    - name: Upload to release
      run: |
        gh release upload --clobber ${{ github.event.release.tag_name }} target/release/${{ matrix.new-name }}